global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'flink'
    static_configs:
      - targets: ['host.docker.internal:9250', 'host.docker.internal:9251',
                  'host.docker.internal:9252', 'host.docker.internal:9253',
                  'host.docker.internal:9254', 'host.docker.internal:9255',
                  'host.docker.internal:9256', 'host.docker.internal:9257',
                  'host.docker.internal:9258', 'host.docker.internal:9259',
                  'host.docker.internal:9260']